<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Command line suite" duration-ms="13755" started-at="2014-06-01T19:55:58Z" finished-at="2014-06-01T19:56:12Z">
    <groups>
    </groups>
    <test name="Command line test" duration-ms="13755" started-at="2014-06-01T19:55:58Z" finished-at="2014-06-01T19:56:12Z">
      <class name="com.any.tests.StubTest">
        <test-method status="FAIL" signature="test()[pri:0, instance:com.any.tests.StubTest@2576a288]" name="test" duration-ms="13734" started-at="2014-06-01T16:55:58Z" finished-at="2014-06-01T16:56:12Z">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[exceptionnnnnnnn]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: exceptionnnnnnnn
	at com.any.tests.StubTest.test(StubTest.java:18)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at com.mgiorda.testng.TestSuiteRunner.run(TestSuiteRunner.java:50)
	at java.lang.Thread.run(Thread.java:745)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test -->
      </class> <!-- com.any.tests.StubTest -->
    </test> <!-- Command line test -->
  </suite> <!-- Command line suite -->
</testng-results>
